#!/usr/bin/env bash
# specs-pr-route.sh <create|delete> <pr-number> — open the mechanical circles-iac PR that adds
# or removes the HTTPRoute serving this PR's specs site at
# https://specs-<N>.circles.teststuff.net (ADR-092: the stack owns *.circles.teststuff.net
# hostnames via HTTPRoutes in circles-iac).
#
# One FLAT file per PR (circles-iac circles/infra/specs-pr-<N>.yaml — the platform ignores
# .spec.source.directory on Applications, so a subdirectory would never sync; see the note in
# circles-iac apps/circles.yaml) on a fixed branch per PR (specs-pr/<N>) — parallel PRs can
# never conflict. Auto-merge on ci-green, the deploy-pin.sh trust level: the route is
# mechanical plumbing to a path prefix only that PR's CI writes.
#
# The route rewrites Host → circles-specs.teststuff.net (Garage web keys the bucket off Host;
# the bucket alias stays circles-specs) and path / → /pr-<N> (the prefix specs-publish.sh
# mirrors to).
#
# Env: GH_TOKEN (contents + pull_requests write on circles-iac — the deploy app token).
set -euo pipefail

ACTION="${1:?usage: specs-pr-route.sh <create|delete> <pr-number>}"
N="${2:?usage: specs-pr-route.sh <create|delete> <pr-number>}"
[[ "$N" =~ ^[0-9]+$ ]] || { echo "::error::pr-number must be numeric, got '$N'"; exit 1; }
: "${GH_TOKEN:?set GH_TOKEN}"

IAC_REPO="teststuffstash/circles-iac"
BRANCH="specs-pr/${N}"
ROUTE_FILE="circles/infra/specs-pr-${N}.yaml"

WORK="$(mktemp -d)"; trap 'rm -rf "$WORK"' EXIT
git clone --quiet --depth 1 "https://x-access-token:${GH_TOKEN}@github.com/${IAC_REPO}.git" "$WORK/iac"
cd "$WORK/iac"
git config user.name "circles-deploy[bot]"
git config user.email "circles-deploy@users.noreply.github.com"
git checkout -q -B "$BRANCH" origin/master

case "$ACTION" in
  create)
    if [ -f "$ROUTE_FILE" ]; then
      echo "route for PR #${N} already on circles-iac master — nothing to do"; exit 0
    fi
    mkdir -p "$(dirname "$ROUTE_FILE")"
    cat > "$ROUTE_FILE" <<EOF
# specs-${N}.circles.teststuff.net → this circles PR's specs-site preview (bucket
# circles-specs, prefix pr-${N}/). Generated by circles scripts/specs-pr-route.sh; removed
# when PR #${N} closes. See circles/infra/README.md.
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: specs-pr-${N}
  namespace: circles
spec:
  parentRefs:
    - name: circles-gateway
  hostnames:
    - specs-${N}.circles.teststuff.net
  rules:
    - matches:
        - path: { type: PathPrefix, value: / }
      filters:
        - type: URLRewrite
          urlRewrite:
            hostname: circles-specs.teststuff.net
            path: { type: ReplacePrefixMatch, replacePrefixMatch: /pr-${N} }
      backendRefs:
        - group: ""
          kind: Service
          name: garage-s3
          namespace: garage
          port: 3902
EOF
    git add "$ROUTE_FILE"
    git commit -q -m "specs-pr: route specs-${N}.circles.teststuff.net (circles PR #${N})"
    TITLE="specs-pr: add route for circles PR #${N}"
    BODY="Automated per-PR specs-site route: https://specs-${N}.circles.teststuff.net → bucket \`circles-specs\` prefix \`pr-${N}/\`. Opened by circles PR #${N}; the close of that PR removes it."
    ;;
  delete)
    if [ ! -f "$ROUTE_FILE" ]; then
      # Route never landed (or already removed). Close a stale open create-PR if one exists.
      STALE="$(gh pr list --repo "$IAC_REPO" --head "$BRANCH" --state open --json number --jq '.[0].number // empty')"
      [ -n "$STALE" ] && gh pr close "$STALE" --repo "$IAC_REPO" --delete-branch \
        --comment "circles PR #${N} closed before this route landed — abandoning."
      echo "no route file for PR #${N} on master — nothing to remove"; exit 0
    fi
    git rm -q "$ROUTE_FILE"
    git commit -q -m "specs-pr: remove route for closed circles PR #${N}"
    TITLE="specs-pr: remove route for closed circles PR #${N}"
    BODY="circles PR #${N} closed — retiring https://specs-${N}.circles.teststuff.net (its \`pr-${N}/\` prefix is purged by the same workflow)."
    ;;
  *)
    echo "::error::unknown action '$ACTION'"; exit 1 ;;
esac

git push -q --force origin "$BRANCH"

PR="$(gh pr list --repo "$IAC_REPO" --head "$BRANCH" --state open --json number --jq '.[0].number // empty')"
if [ -z "$PR" ]; then
  PR="$(gh pr create --repo "$IAC_REPO" --base master --head "$BRANCH" \
    --title "$TITLE" --body "$BODY" | grep -oE '[0-9]+$')"
fi
gh pr merge "$PR" --repo "$IAC_REPO" --auto --squash
echo "→ circles-iac PR #${PR} (${ACTION} route for circles PR #${N}) — auto-merge armed"
